### ISSUE TITLE
documentation: Arbitrary Waveform specification

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/Zahner-Remote-Python#2]
I love the new [ArbitraryProfile example demonstrating the use of `measureProfile()`](https://github.com/Zahner-elektrik/Zahner-Remote-Python/blob/main/Examples/ArbitraryProfile/ArbitraryProfile.ipynb) and I would love to know its limitations. I read the [manual](https://doc.zahner.de/hardware/pp2x2_xpot2.pdf) but did not fully understand it concerning the AC capabilities of the PP2x2.

1. What is the maximum sample rate?
2. Can I use the PP2x2 to generate sine waves? If so, what is the maximum frequency? What is the bandwidth limitation?
3. The manual names the `Impedance Frequency Range` to be up to `200 kHz` – does this mean that the PP2x2 is not affected when I put an AC voltage source in series or an AC current source in parallel if it outputs no harmonics > 200 kHz?

Maybe it is just late and the documentation is actually clear on the point but if not, these information could be added to the data sheet, the README and the example referenced above.

**Comment by maxkrapp1** [comment]
You must note that there are two libraries to control the PP2x2. One library **[zahner_potentiostat](https://github.com/Zahner-elektrik/zahner_potentiostat)**, this repo controls the PP directly via USB. The other library **[thales_remote](https://github.com/Zahner-elektrik/Thales-Remote-Python) controls the Zennium**, which in turn controls the PP remotely via EPC. thales_remote can therefore not control the PP2x2 directly. The following graphic shows this. The manual does not consider the two libraries and applies to both. Only the section in the specifications with SCPI/standalone differs.

![grafik](https://github.com/Zahner-elektrik/Zahner-Remote-Python/assets/56908566/d228a6c7-663f-4684-8c61-14ade5e0704f)

Basically both libraries are completely different and have nothing to do with each other and completely different concepts. Therefore only the functions which are contained in the library are available. So no library contains the functions of the other library. On the respective start pages README.md of the respective repos all functions are listed which are available. And for all available functions there are examples to make it as easy as possible for our customers to get started, if there is no example, then the function does not exist. With zahner_potentiostat only DC primitives are possible no AC.

Now your questions answered one by one:

1. Depending on the library:
 * zahner_potentiostat: limited to 100 Hz.
 * thales_remote: depends on the method, about 100 kSPS maximum.
2. Yes with thales_remote in connection with a Zennium, which generates the sines and outputs them via EPC on the PP2x2. Limitation to 200 kHz described in the manual.
3. This is the specified maximum frequency range when measuring impedance with EPC and Zennium. The PP2x2 is not specified for use case when connecting another AC source in series or in parallel.

measureProfile() uses only the DC primitve of the zahner_potentiostat library and is only available in this library. In thales_remote the [DCSequencer](https://github.com/Zahner-elektrik/Thales-Remote-Python/blob/main/Examples/DCSequencer/DCSequencer.ipynb) is similar to this, but differs fundamentally.

**Comment by maxkrapp1** [comment]
I updated README.md with commit d75d27ae7633eec60255bdfe8f2281bb8222c8a2 and added a large note.

**Comment by maxkrapp1** [comment]
On our overview page, which informs customers about our APIs, we have now also added a sentence to avoid incomprehension in the future.

https://zahner.de/products-details/software/python-c-apis
